### ISSUE TITLE
Add "replaces" to Composer

### ISSUE THREAD

**Issue by szepeviktor** [grogy/PHP-Parallel-Lint#1]
Add "replaces": {"jakub-onderka/php-parallel-lint"} to composer.json

**Comment by grogy** [comment]
Thank for your issue. I solved it in commit https://github.com/grogy/PHP-Parallel-Lint/commit/7758bde18f9ed573ded658740f9ae6772af5159d

**Comment by szepeviktor** [comment]
You're welcome.
